/**:
  ros__parameters:
    map_pcd_file: "/home/amadeusz/AutowareAuto/install/melex_autoware_demos/share/melex_autoware_demos/data/put_a8_parking.pcd"
    map_yaml_file: "/home/amadeusz/AutowareAuto/install/melex_autoware_demos/share/melex_autoware_demos/data/put_a8_parking.yaml"
    map_frame: "map_pcd"
    map_config:
      capacity: 1000000
      min_point:
        x: -1000.0
        y: -1000.0
        z: -3.0
      max_point:
        x: 1000.0
        y: 1000.0
        z: 3.0
      voxel_size:
        x: 3.5
        y: 3.5
        z: 3.5
    viz_map: True
