# config/test.param.yaml
---
filter_transform_os1_128:
  ros__parameters:
    timeout_ms:       110
    pcl_size:         550000
    input_frame_id:  "laser_data_frame"
    output_frame_id: "base_link"
    init_timeout_ms:  5000
    expected_num_subscribers: 2
    expected_num_publishers:  1
    start_angle:            0.0       # radians
    end_angle:              6.28
    min_radius:             3.0      # meters
    max_radius:             150.0
    static_transformer:
      quaternion:
        x:                    0.0
        y:                    0.0
        z:                    0.0
        w:                    1.0
      translation:
        x:                    1.08
        y:                    0.0
        z:                    1.84
