FROM registry.gitlab.com/autowarefoundation/autoware.auto/autowareauto/amd64/ade-foxy:master

RUN useradd -u 1001 ade
RUN echo "ade:ade" | chpasswd
RUN usermod -aG sudo ade
RUN mkhomedir_helper ade
RUN apt-get update
RUN apt-get install openssh-server rsync -y

COPY ./remote_python3 /usr/bin
